### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nxnjitsu** [Stefanuk12/DrFrostMaths#1]

**Comment by Stefanuk12** [comment]
I'll update my tutorial with screenshots soon but yes the quotation marks are needed.

Edit: I have added the screenshots and make sure to download everything so it should look like [this](https://i.imgur.com/aCfWO2J.png) or if you downloaded the whole thing, like [this](https://i.imgur.com/7MuSMXT.png). If it still doesn't work, could you please provide a screenshot of the errors?

**Comment by nxnjitsu** [comment]
.

**Comment by Stefanuk12** [comment]
> thanks for the screenshots
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/63494389/101923981-fe8b3a00-3bc7-11eb-8473-f8eed99d73af.png)
> 
> 
> 
> these are the errors i get in cmd

Could you show me the files where it is installed, I don't think you installed everything. Make sure you have all of the files in a separate folder and run it from there.

**Comment by nxnjitsu** [comment]
![image](https://user-images.githubusercontent.com/63494389/102015326-e267d400-3d52-11eb-82b3-c2615abb0b4c.png)

files are here, node is installed here:

![image](https://user-images.githubusercontent.com/63494389/102015357-0a573780-3d53-11eb-8f7a-a4935d0e7dd7.png)

**Comment by Stefanuk12** [comment]
> ![image](https://user-images.githubusercontent.com/63494389/102015326-e267d400-3d52-11eb-82b3-c2615abb0b4c.png)
> 
> files are here, node is installed here:
> 
> ![image](https://user-images.githubusercontent.com/63494389/102015357-0a573780-3d53-11eb-8f7a-a4935d0e7dd7.png)

I see, run a command prompt by doing: 
1. Press Windows + R
2. Type `cmd`
3. Then press enter or the `OK` button

After that, input and execute this series of commands
`cd "c\Users\nxnji\Desktop\new\drfrostmaths-main\DrFrostMaths-main\Bot"`

`npm i`

`node index.js`

Reply with any issues you have, or preferably at my discord for a quicker reply -> `Stefanuk12#5820`

**Comment by nxnjitsu** [comment]
awesome it works now thanks
