### ISSUE TITLE
can't get _ga cookie on dr frost?

### ISSUE THREAD

**Issue by CyborgPlatypus64** [Stefanuk12/DrFrostMaths#2]

**Comment by Stefanuk12** [comment]
I'm not sure what you mean but I definitely can. Download the [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) extension then it should be the first thing to show.
![image_2021-02-11_161946](https://user-images.githubusercontent.com/42220813/107665061-f6618080-6c84-11eb-9243-5371670987e8.png)

**Comment by CyborgPlatypus64** [comment]
maybe im doing something wrong 

![image](https://user-images.githubusercontent.com/38179621/107679048-003eb000-6c94-11eb-85d9-c13ee8b7027a.png)
